# Generated by Django 5.1.4 on 2025-01-02 06:49

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_gender_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/user/', verbose_name='Image'),
        ),
    ]
