# Generated by Django 5.1.4 on 2025-01-01 11:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=False, populate_from='username'),
        ),
    ]
