# Generated by Django 5.1.4 on 2025-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
